services:

  pager_transmitter_stub:
    image: ${IMAGES_PREFIX:-}pager_transmitter_stub
    build:
      dockerfile: ./Dockerfile
      context: ./pager_transmitter_stub

  php:
    build:
      dockerfile: ./build/frankenphp/Dockerfile
      context: ./webservice
      target: frankenphp_dev
    volumes:
      - ./webservice:/app
      - ./webservice/build/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./webservice/build/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/conf.d/20-app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      INTEL_PAGE_TRANSMITTER_DSN: intelpage://pager_transmitter_stub:6000?secondsBetweenMessages=2
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
  
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
